### PR TITLE
upgrade to STSW-IMG007_2.3.3, and add example for non-blocking loop

### PR DESCRIPTION
**Pull request by hb020**
This is an upgrade to the latest API (that amongst others, has incorporated some of the improvements you had already added to your version based on 2.3.1, see https://github.com/pololu/vl53l1x-st-api-arduino/pull/7/commits/215c70d9dc8cb009cfdb906c76e36da903fa2b8a), and added an example with non-blocking use.

### CODE REVIEW

**Comment by kevin-pololu** [comment]
Thanks for the contribution. The API update looks good. I tried rewriting your additions to the main sketch to organize it a little better and add some more descriptive comments, and I have that in the [api-2.3.3](/pololu/vl53l1x-st-api-arduino/tree/api-2.3.3) branch for now. Could you check that it still works as expected for you?

**Comment by hb020** [comment]
With your changes the example is cleaner indeed. Looks OK to me. Will test in the coming days.

**Comment by hb020** [comment]
Tested, looks OK.

**Comment by OpenUAS** [comment]
Looking forward to the merge, THX!

**Comment by asmitapa** [comment]
can anybody guide me how i can i merge vl53l1x api into nrf52832....code is to written in pure c..i need help on this....it would be really helpful..thank you

**Comment by kevin-pololu** [comment]
@asmitapa The documentation included in the API download from ST's site is probably a good place to start if you haven't read it already. If you need further help, try asking on the [ST community forum](https://community.st.com/s/topic/0TO0X000000BSqxWAG/proximity-sensors).

Alternatively, if you can program your nRF52 through Arduino, you might be able to use the implementation in this repository without any changes, although we have not tested it on that platform.

**Comment by asmitapa** [comment]
@kevin-pololu i am trying to merge vl53l1x API to nrf52....it is giving me an errors to files "vl53l1_platform_user_data.h" "vl53l1_wait.h"
the errors are 
1. unknown type name 'VL53L1_DevData_t'
2. request for member 'CurrentParameters' in something not a structure or union
3. request for member 'LLData' in something not a structure or union
4. request for member 'PalState' in something not a structure or union
 not understanding how to solve these errors..
can you help me out here..??

**Comment by kevin-pololu** [comment]
@asmitapa This repository is an implementation of ST's VL53L1X API for the Arduino platform that we (Pololu) provide to help users get started using the VL53L1X, and the pull request discussion you are commenting in is for reviewing specific changes from another contributor, so it is not an appropriate place for your question. Additionally, we are not familiar with the nRF52 and cannot offer any support for porting the API to that platform. I recommend trying to find help on the ST community forum as I mentioned before and/or finding someone nearby with programming experience who can help you look at the API code and work out how to fix those errors.

**Pull request merged**
